---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/assignment/assignments":
    get:
      summary: List assignments (paginated)
      tags:
      - Assignments
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: limit
        in: query
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: assignments fetched
    post:
      summary: Create an assignment
      tags:
      - Assignments
      parameters: []
      responses:
        '201':
          description: assignment created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                course_schedule_id:
                  type: integer
                due_date:
                  type: string
                  format: date
                title:
                  type: string
                description:
                  type: string
                  nullable: true
                points_possible:
                  type: integer
                status:
                  type: string
              required:
              - course_schedule_id
              - due_date
              - title
              - points_possible
              - status
  "/api/assignment/assignments/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieve an assignment
      tags:
      - Assignments
      responses:
        '200':
          description: found
        '404':
          description: not found
    patch:
      summary: Update an assignment
      tags:
      - Assignments
      parameters: []
      responses:
        '200':
          description: updated
        '422':
          description: invalid request
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                points_possible:
                  type: integer
    delete:
      summary: Delete an assignment
      tags:
      - Assignments
      responses:
        '204':
          description: deleted
        '404':
          description: not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
