default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  schema_search_path: "public,users,assignment,course,reporting"

development:
  <<: *default
  database: rails_proj_development

test:
  <<: *default
  database: rails_proj_test

production:
  primary: &primary_production
    <<: *default
    database: rails_proj_production
    username: rails_proj
    password: <%= ENV["RAILS_PROJ_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_proj_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_proj_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_proj_production_cable
    migrations_paths: db/cable_migrate
